[2024-10-30T04:53:28.490+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T04:53:29.138+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_postgres.load_csv_task manual__2024-10-30T04:53:24.549052+00:00 [queued]>
[2024-10-30T04:53:29.156+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_postgres.load_csv_task manual__2024-10-30T04:53:24.549052+00:00 [queued]>
[2024-10-30T04:53:29.229+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-30T04:53:29.274+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_csv_task> on 2024-10-30 04:53:24.549052+00:00
[2024-10-30T04:53:29.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T04:53:29.291+0000] {standard_task_runner.py:72} INFO - Started process 96 to run task
[2024-10-30T04:53:29.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_postgres', 'load_csv_task', 'manual__2024-10-30T04:53:24.549052+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_pg.py', '--cfg-path', '/tmp/tmpupcmmqfk']
[2024-10-30T04:53:29.302+0000] {standard_task_runner.py:105} INFO - Job 296: Subtask load_csv_task
[2024-10-30T04:53:29.716+0000] {task_command.py:467} INFO - Running <TaskInstance: load_csv_to_postgres.load_csv_task manual__2024-10-30T04:53:24.549052+00:00 [running]> on host 6b6b0d1c2d7e
[2024-10-30T04:53:29.979+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T04:53:24.549052+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T04:53:24.549052+00:00'
[2024-10-30T04:53:29.982+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T04:53:30.150+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-30T04:53:32.764+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T04:53:32.798+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T04:53:32.799+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_csv_to_postgres, task_id=load_csv_task, run_id=manual__2024-10-30T04:53:24.549052+00:00, execution_date=20241030T045324, start_date=20241030T045329, end_date=20241030T045332
[2024-10-30T04:53:33.103+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T04:53:33.130+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T04:53:33.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
