[2024-10-29T13:38:43.452+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T13:38:43.540+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_task scheduled__2024-10-27T20:00:00+00:00 [queued]>
[2024-10-29T13:38:43.568+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_task scheduled__2024-10-27T20:00:00+00:00 [queued]>
[2024-10-29T13:38:43.576+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T13:38:43.716+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_task> on 2024-10-27 20:00:00+00:00
[2024-10-29T13:38:43.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T13:38:43.878+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_task', 'scheduled__2024-10-27T20:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_pg.py', '--cfg-path', '/tmp/tmp8d7nbbd0']
[2024-10-29T13:38:43.894+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2024-10-29T13:38:43.894+0000] {standard_task_runner.py:105} INFO - Job 170: Subtask load_task
[2024-10-29T13:38:44.537+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_task scheduled__2024-10-27T20:00:00+00:00 [running]> on host 69b4f4d5fb60
[2024-10-29T13:38:44.732+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-27T20:00:00+00:00'
[2024-10-29T13:38:44.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T13:38:44.857+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-29T13:38:45.055+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T13:38:45.099+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T13:38:45.102+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=load_task, run_id=scheduled__2024-10-27T20:00:00+00:00, execution_date=20241027T200000, start_date=20241029T133843, end_date=20241029T133845
[2024-10-29T13:38:45.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T13:38:45.274+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T13:38:45.293+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
