[2024-10-29T09:33:37.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T09:33:37.879+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task scheduled__2024-10-27T20:00:00+00:00 [queued]>
[2024-10-29T09:33:37.906+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl_with_excel.transform_task scheduled__2024-10-27T20:00:00+00:00 [queued]>
[2024-10-29T09:33:37.914+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T09:33:37.952+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-27 20:00:00+00:00
[2024-10-29T09:33:37.968+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T09:33:37.977+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2024-10-29T09:33:37.973+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl_with_excel', 'transform_task', 'scheduled__2024-10-27T20:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/pg_my.py', '--cfg-path', '/tmp/tmpdc_9sxk9']
[2024-10-29T09:33:38.010+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask transform_task
[2024-10-29T09:33:38.243+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgres_etl_with_excel.transform_task scheduled__2024-10-27T20:00:00+00:00 [running]> on host fe15dc428079
[2024-10-29T09:33:38.747+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl_with_excel' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-27T20:00:00+00:00'
[2024-10-29T09:33:38.750+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T09:33:39.843+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T09:33:39.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T09:33:39.998+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl_with_excel, task_id=transform_task, run_id=scheduled__2024-10-27T20:00:00+00:00, execution_date=20241027T200000, start_date=20241029T093337, end_date=20241029T093339
[2024-10-29T09:33:40.079+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T09:33:40.148+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T09:33:40.176+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
