[2024-10-29T03:32:30.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T03:32:30.347+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:32:26.471869+00:00 [queued]>
[2024-10-29T03:32:30.358+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:32:26.471869+00:00 [queued]>
[2024-10-29T03:32:30.360+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T03:32:30.388+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-29 03:32:26.471869+00:00
[2024-10-29T03:32:30.399+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_mysql_etl', 'extract_task', 'manual__2024-10-29T03:32:26.471869+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/pg_my.py', '--cfg-path', '/tmp/tmpamgsh9t6']
[2024-10-29T03:32:30.402+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask extract_task
[2024-10-29T03:32:30.427+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T03:32:30.429+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2024-10-29T03:32:30.484+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:32:26.471869+00:00 [running]> on host fe15dc428079
[2024-10-29T03:32:30.842+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_mysql_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T03:32:26.471869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T03:32:26.471869+00:00'
[2024-10-29T03:32:30.849+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T03:32:30.987+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-29T03:32:31.143+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T03:32:31.172+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T03:32:31.174+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_mysql_etl, task_id=extract_task, run_id=manual__2024-10-29T03:32:26.471869+00:00, execution_date=20241029T033226, start_date=20241029T033230, end_date=20241029T033231
[2024-10-29T03:32:31.219+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T03:32:31.290+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29T03:32:31.302+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
