[2024-10-28T15:21:16.329+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T15:21:16.375+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T15:21:14.027830+00:00 [queued]>
[2024-10-28T15:21:16.400+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T15:21:14.027830+00:00 [queued]>
[2024-10-28T15:21:16.401+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-28T15:21:16.436+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-28 15:21:14.027830+00:00
[2024-10-28T15:21:16.443+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-28T15:21:16.447+0000] {standard_task_runner.py:72} INFO - Started process 301 to run task
[2024-10-28T15:21:16.446+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_redshift_etl', 'extract_task', 'manual__2024-10-28T15:21:14.027830+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/reds.py', '--cfg-path', '/tmp/tmpc2lar_gs']
[2024-10-28T15:21:16.449+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask extract_task
[2024-10-28T15:21:16.531+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T15:21:14.027830+00:00 [running]> on host 981556db94ba
[2024-10-28T15:21:16.731+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_redshift_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T15:21:14.027830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T15:21:14.027830+00:00'
[2024-10-28T15:21:16.733+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T15:21:16.774+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-28T15:21:16.883+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T15:21:16.903+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T15:21:16.904+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_redshift_etl, task_id=extract_task, run_id=manual__2024-10-28T15:21:14.027830+00:00, execution_date=20241028T152114, start_date=20241028T152116, end_date=20241028T152116
[2024-10-28T15:21:16.945+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T15:21:16.986+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-28T15:21:16.994+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
