[2024-10-29T22:11:05.641+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T22:11:05.676+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_task scheduled__2024-10-28T20:00:00+00:00 [queued]>
[2024-10-29T22:11:05.692+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_task scheduled__2024-10-28T20:00:00+00:00 [queued]>
[2024-10-29T22:11:05.700+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T22:11:05.778+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-28 20:00:00+00:00
[2024-10-29T22:11:05.796+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=57) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T22:11:05.801+0000] {standard_task_runner.py:72} INFO - Started process 63 to run task
[2024-10-29T22:11:05.814+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'extract_task', 'scheduled__2024-10-28T20:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_pg.py', '--cfg-path', '/tmp/tmpmut4u4ll']
[2024-10-29T22:11:05.822+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask extract_task
[2024-10-29T22:11:06.090+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgres_etl.extract_task scheduled__2024-10-28T20:00:00+00:00 [running]> on host d03394a4d6c1
[2024-10-29T22:11:06.411+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T20:00:00+00:00'
[2024-10-29T22:11:06.417+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T22:11:06.690+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-10-29T22:11:15.149+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T22:11:15.172+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T22:11:15.173+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=extract_task, run_id=scheduled__2024-10-28T20:00:00+00:00, execution_date=20241028T200000, start_date=20241029T221105, end_date=20241029T221115
[2024-10-29T22:11:15.289+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T22:11:15.416+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-29T22:11:15.463+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
