[2024-10-30T03:27:22.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T03:27:23.321+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T03:27:17.689151+00:00 [queued]>
[2024-10-30T03:27:23.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T03:27:17.689151+00:00 [queued]>
[2024-10-30T03:27:23.339+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-30T03:27:23.394+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_excel_task> on 2024-10-30 03:27:17.689151+00:00
[2024-10-30T03:27:23.408+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T03:27:23.407+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_excel_to_postgres', 'load_excel_task', 'manual__2024-10-30T03:27:17.689151+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_pg.py', '--cfg-path', '/tmp/tmp6mz4nx_w']
[2024-10-30T03:27:23.411+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2024-10-30T03:27:23.411+0000] {standard_task_runner.py:105} INFO - Job 240: Subtask load_excel_task
[2024-10-30T03:27:23.537+0000] {task_command.py:467} INFO - Running <TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T03:27:17.689151+00:00 [running]> on host 32eae23b7105
[2024-10-30T03:27:23.813+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_excel_to_postgres' AIRFLOW_CTX_TASK_ID='load_excel_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T03:27:17.689151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T03:27:17.689151+00:00'
[2024-10-30T03:27:23.815+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T03:27:23.933+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-30T03:27:26.681+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T03:27:26.723+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T03:27:26.724+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_excel_to_postgres, task_id=load_excel_task, run_id=manual__2024-10-30T03:27:17.689151+00:00, execution_date=20241030T032717, start_date=20241030T032723, end_date=20241030T032726
[2024-10-30T03:27:26.782+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T03:27:26.847+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T03:27:26.853+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
