[2024-10-28T14:26:14.299+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T14:26:14.349+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T14:26:09.514013+00:00 [queued]>
[2024-10-28T14:26:14.363+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T14:26:09.514013+00:00 [queued]>
[2024-10-28T14:26:14.368+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-28T14:26:14.440+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-28 14:26:09.514013+00:00
[2024-10-28T14:26:14.457+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-28T14:26:14.463+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2024-10-28T14:26:14.467+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_redshift_etl', 'extract_task', 'manual__2024-10-28T14:26:09.514013+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/reds.py', '--cfg-path', '/tmp/tmpoqv8641q']
[2024-10-28T14:26:14.469+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask extract_task
[2024-10-28T14:26:14.604+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_redshift_etl.extract_task manual__2024-10-28T14:26:09.514013+00:00 [running]> on host 981556db94ba
[2024-10-28T14:26:15.088+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_redshift_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T14:26:09.514013+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T14:26:09.514013+00:00'
[2024-10-28T14:26:15.104+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T14:26:15.418+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-28T14:26:15.998+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T14:26:16.030+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T14:26:16.031+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_redshift_etl, task_id=extract_task, run_id=manual__2024-10-28T14:26:09.514013+00:00, execution_date=20241028T142609, start_date=20241028T142614, end_date=20241028T142616
[2024-10-28T14:26:16.175+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T14:26:16.250+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-28T14:26:16.270+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
